apiVersion: v1
data:
  fluent.conf: |2-

    @include kubernetes.conf

    <filter **>
      @type grep
      <exclude>
        key kubernetes
        pattern ^kube-system$
      </exclude>
    </filter>
    <match **>
      @type copy
      <parse>
        @type multiline
        format_firstline /^Oplog/
      </parse>
      <store>
        @type gelf
        host "#{ENV['GELF_HOST']}"
        port "#{ENV['GELF_PORT']}"
        protocol "#{ENV['GELF_PROTOCOL']}"
        <buffer>
          flush_mode immediate
          #flush_interval 10s
          #retry_type exponential_backoff
          flush_thread_count 8
        </buffer>
      </store>
      <store>
        @type s3
        aws_key_id "#{ENV['S3_AWS_KEY_ID']}"
        aws_sec_key "#{ENV['S3_AWS_SEC_KEY']}"
        s3_bucket "#{ENV['S3_BUCKET']}"
        s3_region "#{ENV['S3_REGION']}"

        path logs/%Y/%m/%d/
        s3_object_key_format %{path}%{time_slice}_%{index}.%{file_extension}
        
        <buffer time>
          @type file
          path /var/log/fluent/s3
          timekey 3600 # 1 hour partition
          timekey_wait 10m
          timekey_use_utc true # use utc
        </buffer>
        <format>
          @type json
        </format>
      </store>
    </match>
  kubernetes.conf: |-
    <match fluent.**>
      @type null
    </match>

    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag kubernetes.*
      format json
      read_from_head true
    </source>

    <source>
      @type tail
      format /^(?<time>[^ ]* [^ ,]*)[^\[]*\[[^\]]*\]\[(?<severity>[^ \]]*) *\] (?<message>.*)$/
      time_format %Y-%m-%d %H:%M:%S
      path /var/log/salt/minion
      pos_file /var/log/fluentd-salt.pos
      tag salt
    </source>

    <source>
      @type tail
      format syslog
      path /var/log/startupscript.log
      pos_file /var/log/fluentd-startupscript.log.pos
      tag startupscript
    </source>

    <source>
      @type tail
      format /^time="(?<time>[^)]*)" level=(?<severity>[^ ]*) msg="(?<message>[^"]*)"( err="(?<error>[^"]*)")?( statusCode=($<status_code>\d+))?/
      path /var/log/docker.log
      pos_file /var/log/fluentd-docker.log.pos
      tag docker
    </source>

    <source>
      @type tail
      format none
      path /var/log/etcd.log
      pos_file /var/log/fluentd-etcd.log.pos
      tag etcd
    </source>

    <source>
      @type tail
      format kubernetes
      multiline_flush_interval 5s
      path /var/log/kubelet.log
      pos_file /var/log/fluentd-kubelet.log.pos
      tag kubelet
    </source>

    <source>
      @type tail
      format kubernetes
      multiline_flush_interval 5s
      path /var/log/kube-proxy.log
      pos_file /var/log/fluentd-kube-proxy.log.pos
      tag kube-proxy
    </source>

    <source>
      @type tail
      format kubernetes
      multiline_flush_interval 5s
      path /var/log/kube-apiserver.log
      pos_file /var/log/fluentd-kube-apiserver.log.pos
      tag kube-apiserver
    </source>

    <source>
      @type tail
      format kubernetes
      multiline_flush_interval 5s
      path /var/log/kube-controller-manager.log
      pos_file /var/log/fluentd-kube-controller-manager.log.pos
      tag kube-controller-manager
    </source>

    <source>
      @type tail
      format kubernetes
      multiline_flush_interval 5s
      path /var/log/kube-scheduler.log
      pos_file /var/log/fluentd-kube-scheduler.log.pos
      tag kube-scheduler
    </source>

    <source>
      @type tail
      format kubernetes
      multiline_flush_interval 5s
      path /var/log/rescheduler.log
      pos_file /var/log/fluentd-rescheduler.log.pos
      tag rescheduler
    </source>

    <source>
      @type tail
      format kubernetes
      multiline_flush_interval 5s
      path /var/log/glbc.log
      pos_file /var/log/fluentd-glbc.log.pos
      tag glbc
    </source>

    <source>
      @type tail
      format kubernetes
      multiline_flush_interval 5s
      path /var/log/cluster-autoscaler.log
      pos_file /var/log/fluentd-cluster-autoscaler.log.pos
      tag cluster-autoscaler
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>
kind: ConfigMap
metadata:
  name: fluentd-configmap
  namespace: kube-system
